version: '3.3'

services:
  mongo:
    image: mongo:4.4
    container_name: zk-health-mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
